In [18]:
import pandas as pd
from fuzzywuzzy import process

# List of valid Mexican state names
valid_states = [
    "CIUDAD DE MEXICO", "HIDALGO", "ESTADO DE MEXICO", "QUERETARO", "QUINTANA ROO", 
    "VERACRUZ", "YUCATAN", "CHIAPAS", "JALISCO", "GUANAJUATO", "PUEBLA",
    # Add all other valid Mexican state names here



]

# List of correct Mexican state names and mappings for common incorrect variations
correct_states = {
    "CDMX": "CIUDAD DE MEXICO",
    "QRO.": "QUERETARO",
    "CDMX.": "CIUDAD DE MEXICO",
    "EDMX": "CIUDAD DE MEXICO",
    "MX": "CIUDAD DE MEXICO",
    "D. F.": "CIUDAD DE MEXICO",
    "DF": "CIUDAD DE MEXICO",
    "D, F.": "CIUDAD DE MEXICO",
    "EDO Q. ROO": "QUINTANA ROO",
    "HGO": "HIDALGO",
    "HGO.": "HIDALGO",
    "SN LUIS POTOSI": "SAN LUIS POTOSI",
    "EDO MEX": "ESTADO DE MEXICO",
    "EDO VER": "VERACRUZ",
    "EDO HGO": "ESTADO DE MEXICO",
    "EDO GRO": "GUERRERO",
    "LA PAZ": "BAJA CALIFORNIA"
    "HIDALGO": "HIDALGO",
    "ESTADO DE MEXICO": "ESTADO DE MEXICO",
    "QUERETARO": "QUERETARO",
    "CANCUN QUINTANAROO": "QUINTANA ROO",  # Correcting this entry
    "QUINTANAROO": "QUINTANA ROO",         # Another variation of "QUINTANA ROO"
    "VERACRUZ DE IGNACIO DE LA LLAVE": "VERACRUZ",  # Correcting Veracruz name
    # Additional mappings can be added here as needed
}

# Load the CSV file from the current working directory
df = pd.read_csv('customer.csv')

# Standardize the "Location" column to uppercase
df['Location'] = df['Location'].str.upper()

# Replace non-standard or incorrect names with correct ones using the updated mapping
df['Location'] = df['Location'].replace(correct_states)

# Function to match incorrect names to valid state names using fuzzy matching
def match_state(state):
    if isinstance(state, str):  # Only apply fuzzy matching if the value is a string
        match, score = process.extractOne(state, valid_states)
        if score >= 80:  # Set a threshold score for matching (e.g., 80%)
            return match
    return state  # If not a string or no good match, return the original value

# Apply fuzzy matching to the "Location" column
df['Location'] = df['Location'].apply(match_state)

# Remove rows where the 'Location' column is empty or contains only whitespace
df = df[df['Location'].str.strip() != ""]

# Delete the 'Kcustomer' column
# df = df.drop(columns=['Kcustomer'])

# Save the corrected dataframe to a new CSV file in the same directory
df.to_csv('customer_corrected.csv', index=False)

df.head()

    TipoC   Customer    Class Kcustomer          Location
0  V Ccte  Customer1  Class01     Local  CIUDAD DE MEXICO
1  V Ccte  Customer2  Class01   Foraneo           HIDALGO
2  V Ccte  Customer3  Class01     Local  CIUDAD DE MEXICO
3  V Ccte  Customer4  Class01   Foraneo  ESTADO DE MEXICO
4  V Ccte  Customer5  Class01   Foraneo         QUERETARO